name: MasonX-Profiler
module_name: MasonX::Profiler
version: 0.01
abstract: Mason per-component profiler
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
requires:
  HTML::Mason: 0
  Time::HiRes: 0
private:
  directory:
    - inc
generated_by: Module::Install version 0.24
