---
abstract: 'Mason per-component profiler'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MasonX-Profiler
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Mason: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.07'
